# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: source/conf.py
  fail_on_warning: true

formats:
- pdf

python:
  install:
  - requirements: requirements.txt

search:
  ranking:
    methods/*: 10
    settings/*: 9
    document/android/*: 9
    framework/*: 8
    document/*: 7
    references.html: 5
    "*/interface.html": 0
    browser.html: -1
    installation.html: -2
  ignore:
  - index.html
  - "*/index.html"